server:
  port: 8082
  servlet:
    context-path: /ui
    session:
      cookie:
        name: UISESSION

security:
  oauth2:
    client:
      clientId: CilentId
      clientSecret: Secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/rest/hello

spring:
  thymeleaf:
    cache: false